### ISSUE TITLE
Build Angular Front End

### ISSUE THREAD

**Issue by nprail** [mcpr/mcpr#12]
Build out the Angular.js front end. 

## Tasks
- [x] Build File Structure
- [x] Add Build Scripts
- [x] Build Front End
