### ISSUE TITLE
Build API

### ISSUE THREAD

**Issue by nprail** [mcpr/mcpr#2]
Build out data schema and the API. 

### Tasks
- [x] Connect to MongoDB
- [x] Build API
  - [x] Plugins API
  - [x] Versions API
  - [x] Users API
  - [x] Auth API

### API Endpoints `/api`
- [x] `GET /plugins` - List Plugins
  - [x] `POST /plugins` - Create Plugin (Requires Auth)
  - [x] `PUT /plugins/:pluginId` - Update Plugin (Requires Auth)
  - [x] `GET /plugins/:pluginId` - Get Single Plugin
    - [x] `GET /plugins/:pluginId/download` - Download Plugin

- [x] `GET /versions` - Get Plugin Versions
  - [x] `POST /versions` - Create Plugin Version (Requires Auth)
  - [x] `PUT /versions/:pluginID/:versionID` - Update Plugin Version (Requires Auth)
  - [x] `GET /versions/:pluginID/:versionID` - Get Single Plugin Version
  - [x] `GET /versions/:pluginID` - Get Plugin Versions
  - [x] `POST /versions/:pluginID/:versionID/upload` - Upload Plugin Version (Requires Auth)
  - [x] `GET /versions/:pluginID/:versionID/download` - Download Version

- [x] `GET /users` - List Users
  - [x] `/users/me` - Account
    - [x] `POST /users/me/login` - Login
    - [x] `POST /users/me/signup` - Signup
    - [x] `GET /users/me/profile` - Get Current Users's Profile  (Requires Auth)
    - [x] `PUT /users/me/profile` - Update Current User's Profile (Requires Auth)
    - [x] `PUT /users/me/password` - Update Current User's Password (Requires Auth)
  - [x] `GET /users/:username` - Get Single User's Profile
    - [x] `GET /users/:username/plugins` - List User's Plugins
