### ISSUE TITLE
Version API

### ISSUE THREAD

**Issue by nprail** [mcpr/mcpr#24]
Version the API! 

Move the API to a `v1` subfolder and change the address to `/api/v1`.

### To-Do
- [x] Move API to `v1` subfolder of `api`
- [x] Change Address to `/api/v1`
- [x] Fix File References
